### PR TITLE
Fixes issue #90, #91, #92

### LINKED ISSUE #91: To implement the service /v1/switch-redundant-transmitter-pair-off
- [ ] After receiving the request , before processing the callbacks , a request-id shall be generated and sent to the requestor as a response.
- [ ] This generated request-id and the requestor details shall be stored in a temporary data store to send the final result as a callback to the requestor

For example , two maps shall be included to temporarily maintained in a global datastore, 
```js
	switchOffTXPairRequestMap // to store and map the generated request-id to the requestor details
	switchOffTXPairTransactionMap // to store and map the consequent callback’s request-id to the request-id of the initial request

        switchOffTXPairRequestMap.set(“main request-id” , {“requestor-ip”,”port”,”callback url”}} //The generated request-id and the requestor details shall be stored, 
```

After responding with the request-id to the requestor , process the following callbacks, 

### Getting information about the parallel links
If a parallel link is available for the provided link-id , then the provided link's transmitters shall be switchedOFF so that power will be saved. So , to check whether a parallel link is available , 
- [ ] Perform the callback RequestForSwitchingRedundantTransmitterPairOffInitiatesTransaction.GetInfoAboutParallelLinks
This is a call to the API /v1/provide-transmitter-status-of-parallel-links in the AIPS application itself via the REST layer. 
While formulating the request body , the value for the "requestor-receive-operation AIPS::/v1/receive-power-saving-activation-status " attribute needs to be hardcoded as there is no pointer available to trace it automatically.
Response for this callback is again a request-id which shall be included in the transaction management map.
For example 
switchOffTXPairTransactionMap.set(“callback-request-id  : “main request-id” }

> :information_source: Further , if a parallel link is available , then  AIPS::/v1/provide-transmitter-status-of-parallel-links will inform AIPS via the API AIPS::/v1/receive-power-saving-activation-status.

### PR DESCRIPTION
**Pull request by vanithavalluripalli9**
Fixes To implement the service /v1/switch-redundant-transmitter-pair-off #91
Fixes To implement the service /v1/provide-transmitter-status-of-parallel-links #90,
Fixes To implement the service /v1/receive-transmitter-status-of-parallel-links #92

### CODE REVIEW

File: server/service/individualServices/LinkAnalysis/PrepareSwitchRedundantTransmitterPairOffForwarding.js [hunk 1]
```diff
@@ -0,0 +1,371 @@
...
+ * Formulates status of link
+ * @param {List}    parallelLinks contains parallel links list .
+ * @param {String}  linkId Id of the initial link. 
+ * @param {Object}  requestHeaders Holds information of the requestHeaders like Xcorrelator , CustomerJourney,User etc.
+ * @param {Integer} traceIndicatorIncrementer traceIndicatorIncrementer to increment the trace indicator
+ */
+async function formulateStatusOfLink(parallelLinks, intialLinkId, requestHeaders, traceIndicatorIncrementer) {
+    let statusOfLink = "UndefinedState";
+    let statusOfLinkAndTraceIndicatorIncrementer = {};
+    if (parallelLinks.length === 2) {
```
Comment (IswaryaaS) [inline server/service/individualServices/LinkAnalysis/PrepareSwitchRedundantTransmitterPairOffForwarding.js:171]: As per diagram, [switchRedundantTransmitterIsOff](https://raw.githubusercontent.com/openBackhaul/AirInterfacePowerSaver/develop/spec/diagrams/05_LinkRelatedSwitchingOperation/500_switchRedundantTransmitterPairOff.png), the check shall be included for parallelLinks>=2
image

Comment (IswaryaaS) [reply server/service/individualServices/LinkAnalysis/PrepareSwitchRedundantTransmitterPairOffForwarding.js:171]: Also, we need to check once if it is >=2 or ==2

**Review by IswaryaaS — CHANGES_REQUESTED** [review]

File: server/service/individualServices/LinkAnalysis/ReactivateTransmittersOfLink.js [hunk 2]
```diff
@@ -262,138 +220,12 @@ async function ReactivateTransmitterOfLinkResponse(statusOfLink, requestorData,
             requestorData["requestor-port"],
             requestorData["requestor-receive-operation"],
             httpRequestHeader,
-            requestBody,
```
[the remark this answers is not in the document]
Comment (vanithavalluripalli9) [reply server/service/individualServices/LinkAnalysis/ReactivateTransmittersOfLink.js]: Done

File: server/service/individualServices/EventDispatcherWithResponse.js [hunk 3]
```diff
@@ -73,4 +75,46 @@ exports.dispatchEvent = async function(operationClientUuid, httpRequestBody, use
...
+ * @param {Integer} traceIndicatorIncrementer traceIndicatorIncrementer to increment the trace indicator
+ */
+exports.BuildAndTriggerRestRequestToRequestor = async function (requestorProtocol, requestorAddress, requestorPort, requestorReceiveOperation, requestHeaders, requestBody, httpMethod, traceIndicatorIncrementer) {
+    let url = requestorProtocol.toLowerCase() + "://" + requestorAddress + ":" + requestorPort +
+        requestorReceiveOperation;
+
+    /******************************************************************************************************************
+     *  Fetching of Operation key to be updated based on the decision made on issue
+     *  https://github.com/openBackhaul/AirInterfacePowerSaver/issues/114
+     *****************************************************************************************************************/
```
[the remark this answers is not in the document]
Comment (vanithavalluripalli9) [reply server/service/individualServices/EventDispatcherWithResponse.js]: Done

File: server/service/individualServices/LinkAnalysis/ReactivateTransmittersOfLink.js [hunk 4]
```diff
@@ -1,9 +1,10 @@
 'use strict';
 
 const createHttpError = require("http-errors");
-const PssAttributes = require('./powerSavingAttributes');
```
[the remark this answers is not in the document]
Comment (vanithavalluripalli9) [reply server/service/individualServices/LinkAnalysis/ReactivateTransmittersOfLink.js]: Done

File: server/service/individualServices/LinkAnalysis/PrepareSwitchRedundantTransmitterPairOffForwarding.js (hunk 1 above)
Comment (vanithavalluripalli9) [reply server/service/individualServices/LinkAnalysis/PrepareSwitchRedundantTransmitterPairOffForwarding.js]: Changed the check as per diagram . But , as per discussion with testing team there will not be links >2

Comment (IswaryaaS) [reply server/service/individualServices/LinkAnalysis/PrepareSwitchRedundantTransmitterPairOffForwarding.js]: @PrathibaJee , @vanithavalluripalli9  shall we create an issue for updating this concept in diagram

File: server/service/individualServices/LinkAnalysis/PrepareProvideTransmitterStatusOfParallelLinksForwarding.js [hunk 5]
```diff
@@ -0,0 +1,347 @@
...
+            let parallelLinkDetails = {};
+            let transmitterStatusList = [];
+            let linkId = parallelLinks[i];
+            if (parallelLinks.length > 1) {
+
+                /****************************************************************************************
+                 *  Fetching linkEndPointsDetails mountName , uuid , localId 
+                 ****************************************************************************************/
+
+                let linkEndPointsDetailsList = await determineLinkEndPoints(linkId, requestHeaders, traceIndicatorIncrementer++);
```
Comment (IswaryaaS) [inline server/service/individualServices/LinkAnalysis/PrepareProvideTransmitterStatusOfParallelLinksForwarding.js:151]: as discussed, since we have same implementation in linkRelatedSwitchingoperation.js, we shall transfer this function to prepareForwardingAutomation.js file

**Review by IswaryaaS — APPROVED** [review]

**Review by IswaryaaS — CHANGES_REQUESTED** [review]
requesting changes for https://github.com/openBackhaul/AirInterfacePowerSaver/pull/120#discussion_r1448618050

**Review by IswaryaaS — APPROVED** [review]
